version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    environment:
      - ENVIRONMENT=development
      - PYTHONPATH=/
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000

  admin-frontend:
    build:
      context: ./admin-frontend
    ports:
      - "5174:5173"
    volumes:
      - ./admin-frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
